backend:
  name: github
  repo: Shqiptar334/Akomorad.be
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "paginas"
    label: "Pagina's"
    editor:
      preview: false
    files:

      - label: "Home"
        name: "index"
        file: "index.html"
        fields:
          - label: "HTML"
            name: "body"
            widget: "text"

      - label: "Rechtszaken"
        name: "rechtszaken"
        file: "rechtszaken.html"
        fields:
          - label: "HTML"
            name: "body"
            widget: "text"

      - label: "Rollen"
        name: "rollen"
        file: "rollen.html"
        fields:
          - label: "HTML"
            name: "body"
            widget: "text"

      - label: "Video"
        name: "video"
        file: "video.html"
        fields:
          - label: "HTML"
            name: "body"
            widget: "text"

      - label: "IDkaarten"
        name: "idkaarten"
        file: "IDkaarten.html"
        fields:
          - label: "HTML"
            name: "body"
            widget: "text"
