backend:
  name: github
  repo: Shqiptar334/Akomorad.be
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test"
    files:
      - label: "Testpagina"
        name: "testpagina"
        file: "test.md"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
